# Generated by Django 4.1.4 on 2022-12-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
